version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - './db:/data/db'

  user-service:
    container_name: user-ms
    build:
      context: .
    command: npm run start:user
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "3001:3001"

  book-service:
    container_name: book-ms
    build:
      context: .
    command: npm run start:book
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "3002:3002"

  bookshelf-service:
    container_name: bookshelf-ms
    build:
      context: .
    command: npm run start:bookshelf
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "3003:3003"

  rating-service:
    container_name: rating-ms
    build:
      context: .
    command: npm run start:rating
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "3004:3004"
